1) Parse float as CurrentCulture else InvariantCulture
NicholasNoise/dBASE.NET pull request #2
Opened 2019-10-16 13:58 UTC by jbzorg

1) Исправлен парсинг float - сначала предпринимается попытка распарсить как _CultureInfo.CurrentCulture_, затем как _CultureInfo.InvariantCulture_.
2) Тесты _DBase4WithMemo_ выполняются успешно при _CultureInfo.CurrentCulture != CultureInfo.InvariantCulture_

2019-10-17 09:29 UTC, NicholasNoise requested changes

2019-10-17 09:29 UTC, NicholasNoise commented on dBASE.NET/Encoders/FloatEncoder.cs
> +            return float.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var res) ? res : float.Parse(text, CultureInfo.InvariantCulture);
По документации формат дб через точку, соответственно, в Encode - тоже.

2019-10-17 12:57 UTC, jbzorg commented on dBASE.NET/Encoders/FloatEncoder.cs
> +            return float.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out var res) ? res : float.Parse(text, CultureInfo.InvariantCulture);
Исправлено, теперь всегда используется _CultureInfo.InvariantCulture_.
Однако, обработчик float, в отличие от обработчика numeric игнорирует настройку _Precision_ для поля - не знаю на сколько это критично. Если добавить обработку - сломается совместимость, так как по умолчанию _Precision_ == 0.

Кроме этого, судя по коду обработчика numeric - _Precision_ используется некорректно - в качестве _Scale_. Правильней было бы либо поменять использование этой настройки (что breaking change) либо переименовать в _Scale_.
Либо забить и считать что так исторически сложилось :)

2019-10-18 02:58 UTC, NicholasNoise approved these changes

2019-10-18 02:59 UTC, merged